config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'homes#top'
  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence: true
  validates :description, presence: true
  validates :action, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to post_path(post)
  end
  
  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to post_path(post)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  def destroy
    PostComment.find_by(id: params[:id],post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private
    def post_comment_params
      params.require(:post_comment).permit(:comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = PostComment.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :description, :action)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 mt-5 mx-auto">
      <h1>TrashBoxトップページ</h1>
      <p>あなたの不満や悩みなどマイナスの感情をシェアして楽になろう!<br>
      次のアクションを考えて前向きになろう！</p>
      <% if signed_in? %>
        <%= link_to "投稿する", new_post_path, class:"btn btn-info" %>
        <%= link_to "投稿一覧", posts_path, class:"btn btn-success" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class:"btn btn-info" %>
        <%= link_to "新規登録", new_user_registration_path, class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", posts_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '投稿する', new_post_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container-fluid py-4 mw-md">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">Trash編集</h5>
      <div class="form-body p-4">
        <%= link_to "戻る", post_path(@post), class:"btn btn-info" %>
        <% if @post.errors.any? %>
          <%= @post.errors.count %>件のエラーが発生しました
          <% @post.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%=form_with model:@post, local:true do |f| %>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_area :description, class:"form-control", rows:"3", placeholder:"説明" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :action, class:"form-control", placeholder:"これからどうする？" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.submit '保存',class:"btn btn-lg btn-block btn-info mt-4" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row mx-auto card-container py-5">
  <% @posts.each do |post| %>
    <div class="col-md-4 h-100">
      <div style="min-height: 200px" class="card p-3 mx-auto mt-4 shadow-lg">
        <div class="card-body">
          <%= link_to post_path(post.id) do %>
            <p>タイトル：<%= post.title %></p>
            <p>これからどうする？：<%= post.action %></p>
            <%= link_to user_path(post.user_id) do %>
              <span><i class="fas fa-user"></i> <%= post.user.name %></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">Trash投稿</h5>
      <div class="form-body p-4">
        <% if @post.errors.any? %>
          <%= @post.errors.count %>件のエラーが発生しました
          <% @post.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%=form_with model:@post, local:true do |f| %>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :title, class:"form-control", placeholder:"タイトル" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_area :description, class:"form-control", placeholder:"説明" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :action, class:"form-control", rows:"3", placeholder:"これからどうする？" %>
          </div>
          <div class="input-group mb-3 mt-4">
            <%= f.submit '投稿', btn btn-block btn-info mt-4" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card col-md-8 mx-auto h-100 p-2 mt-4 shadow-lg">
  <div class="card-body">
    <%= link_to "戻る", posts_path, class:"btn btn-info mb-4" %>
    <div class="post-body">
      <p class="mb-0">タイトル</p>
      <p class="border"><%= @post.title %></p>
      <p class="mb-0">説明</p>
      <p class="border"><%= @post.description %></p>
      <p class="mb-0">これからどうする？</p>
      <p class="border"><%= @post.action %></p>
      <p>
        <%= link_to user_path(@post.user) do %>
          <span class="mr-1"><i class="fas fa-user"></i><%= @post.user.name %><span>
        <% end %>：
        <%= @post.created_at.strftime('%Y/%m/%d') %>
      </p>
      <div class="comments">
        <% if @post.favorited_by?(current_user) %>
          <p>
            <%= link_to post_favorites_path(@post), method: :delete do %>
              ♥<%= @post.favorites.count %> いいね
            <% end %>
          </p>
        <% else %>
          <p>
            <%= link_to post_favorites_path(@post), method: :post do %>
              ♡<%= @post.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>
        <p>コメント件数：<%= @post.post_comments.count %></p>
        <%= form_with(model:[@post,@post_comment], local: true) do |f| %>
          <div class="form-group">
            <%= f.text_field :comment, placeholder:"コメントを残す", class:"form-control" %>
            <%= f.submit "コメントを送信する", class:"btn btn-sm btn-info mt-1" %>
          </div>
        <% end %>
      </div>
      <% if @post.user_id == current_user.id %>
        <%= link_to "削除", post_path(@post), method: :delete,data: { confirm: "投稿を削除してもよろしいですか？" }, class:"btn btn-danger mr-2" %> 
        <%= link_to "編集", edit_post_path(@post),class:"btn btn-success" %>
      <% end %> 
    </div> 
  </div>
  
</div>

<% @post.post_comments.each do |post_comment| %>
<div class="show-comments card col-md-8 mx-auto mt-3">
  <div class="card-body">
    <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %> <%= post_comment.comment %>
    <% if post_comment.user == current_user %>
      <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "btn btn-sm btn-danger" %>
    <% end %>
  </div>
</div>
<% end %>
  

app/views/users/edit.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">プロフィール編集</h5>
      <div class="form-body p-4">
        <% if @user.errors.any? %>
          <%= @user.errors.count %>件のエラーが発生しました
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <%= link_to "メールアドレス・パスワードを編集する", edit_user_registration_path %>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group mb-3 mt-4">
            <h5 class="form-label">ユーザーネーム</h5>
            <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control", placeholder: "名前" %>
          </div>
          <div class="form-group mb-3 mt-4">
            <h5 class="form-label">プロフィール</h5>
            <%= f.text_area :profile, autofocus: true, id:"inputProfile",class:"form-control", rows:"5", placeholder: "プロフィール" %>
          </div>
          
          <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-container w-50 mt-5 mx-auto">
  <h3 class="profile-name"><%= @user.name %></h3>
  <p><%= @user.profile %></p>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>
<div class="card-container py-3">
  <% @posts.each do |post| %>
    <div class="card w-50 p-3 mx-auto mt-4 shadow-lg">
      <%= link_to post_path(post.id) do %>
        <p>タイトル：<%= post.title %></p>
        <p>これからどうする？：<%= post.action %></p>
        <%= link_to user_path(post.user_id) do %>
          <span><i class="fas fa-user"></i> <%= post.user.name %></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>